### ISSUE TITLE
0.2.3 -> 0.2.4 drops support for React 0.12

### ISSUE THREAD

**Issue by maiflai** [skratchdot/react-bootstrap-daterangepicker#13]
Hi,

My project declares separate dependencies for both `react` and `react-bootstrap-daterangepicker`.

I had declared these dependencies using the `~` operator to indicate that minor updates should be taken automatically (and I think that using the `^` operator would have the same effect given that both these dependencies are at the 0.x.x stage).

The automated build failed when 0.2.4 was released. I think that the change to drop support for React 0.12 is actually a breaking change, and therefore 0.2.4 should have been released as 0.3.0.

I have now stated the dependency as exactly 0.2.3, and my automated build has returned to normal.

I'm now investigating the use of npm shrinkwrap and explicit versioning to avoid this sort of thing in future, but I'd like to understand whether this particular break was accidental or by design? 

Further, is it possible to release a new 0.2.5 and retain compatibility with React 0.12, or does the current codebase require 0.13?

Thanks in advance,
Stu.

**Comment by skratchdot** [comment]
Hey.  Sorry about this change.  I've had things like this bite me in the past.  I was worried about things not working w/ 0.12.x at some point, so bumped up the required react version to 0.13.x.  With semantic versioning, all 0.x.x versions are considered unstable (and can change at anytime).  At one point in time I didn't know that.  I still think it's kind of cheating, and the versioning in this project doesn't really make any sense.  I definitely should've bumped up the minor version since this was more than a patch.

Anyways, I'll publish a new version, and change the requirement back to >= 0.12.x.  I don't think there's anything 0.13 specific that would cause an issue.  I also need some tests in this project at some point.

It's weird writing something that requires react b/c there are still alot of breaking changes.  I remember having issues w/ react-bootstrap when react made a few big changes in either 0.11.x or 0.12.x.  It gets weird trying to catch up.  I think that project decided to always bump their required react version to the latest version of react.

SIDENOTE: for a lot of my node projects, I'll use `npm-dview --update` when I do development locally (a tool I wrote that checks your package.json to see if it's up to date.  If I'm publishing a project to production, using npm shrinkwrap is a good idea...

**Comment by skratchdot** [comment]
I also changed the version to catch 0.13.x alpha/beta versions (since someone submitted a pull request for 0.13.x support a while back).  I used: semver.npmjs.com to check that I am catching all 0.12.x and 0.13.x versions now...

**Comment by maiflai** [comment]
Thanks for the quick turnaround, much appreciated.
