### ISSUE TITLE
How do I programatically modify minDate and maxDate?

### ISSUE THREAD

**Issue by kensplanet** [skratchdot/react-bootstrap-daterangepicker#225]
I have the DateRangePicker setup as below,
How do I programatically modify the `minDate` and `maxDate`?

something like `this.fromPicker.minDate = <some date>`

```
  <DateRangePicker ref={(picker) => this.fromPicker = picker} onApply={this._onCustomStartDateChange} initialSettings={{
                    startDate: this.state.customStartDate,
                    minDate: minStartDate,
                    maxDate: maxStartDate,
                    singleDatePicker: true,
                    autoApply: true
                }}>

        <div className="input-group date" id="datetimepicker">
                        <input ref="customStartDate" id="customStartDate" type="text"
                            style={{ backgroundColor: "#fff", cursor: "pointer" }}
                            className="form-control" disabled="disabled"
                            autoComplete="off" value={startDateStr}/>
        </div>
 </DateRangePicker>
```

**Comment by skratchdot** [comment]
It's very unintuitive/complicated, but I have an example of how to "change initialSettings":

https://projects.skratchdot.com/react-bootstrap-daterangepicker/?path=/story/daterangepicker--change-initialsettings-range-data

https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/master/stories/index.js#L218-L284

The example above changes the "range" setting, but you can use something similar for the "minDate"/"maxDate".  What you need to do is force the component to unmount/remount.  There are a number of ways to do this, but 1 way is by using a "key" attribute on the `<DateRangePicker />`.  Whenever you want to re-mount the component, you can change the key.

That is very hacky, but seems to work.  You might want to google "react how to force a remount" or something because there might be better strategies.

You might ask: WHY IS THIS NEEDED?

It's because this library isn't something I wrote from scratch- so it's not a typical component- it's just a "dumb wrapper" around the upstream lib that I created back in 2014 b/c I used it in a project and figured it might be easy for other people to use.  So there are lots of edge cases that don't work well in a react setting, and that's why I moved everything into an "intialSettings" prop- to let people know that those values aren't meant to be changed after the initial render.  If you _need_ to change them, then you'll need to unmount and re-mount the component.

Sorry for the delayed response- I'm just now seeing your message!
